name = "static-api-v1-poc0"
main = "src/index.ts"
compatibility_date = "2023-12-18"

[[r2_buckets]]
binding = "STATIC_API_V1"
bucket_name = "${R2_BUCKET_NAME}"

# Necessary secrets:
# - R2_BUCKET_NAME
# - AUTH_PRIVATE_KEY
