on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Not currently needed, but will in near future
      - name: NodeJS setup
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      # Testing Turborepo - probably overkill - NPM Workspaces would work just fine as well
      # v0 POC target web app only
      - name: Disable Turborepo Telemetry
        run: npx turbo telemetry disable
      - name: Lint
        run: npx turbo run lint --filter=web
      - name: Build
        run: npx turbo run build --filter=web
        env:
          WORKER_URL: ${{ secrets.WORKER_URL }}
          PROFILES_API_ENDPOINT: ${{ secrets.PROFILES_API_ENDPOINT }}
          AUTH_PRIVATE_KEY: ${{ secrets.AUTH_PRIVATE_KEY }}
          WAF_AUTH_VERIFY_KEY: ${{secrets.WAF_AUTH_VERIFY_KEY }}
      - name: Publish Webapp
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN_PAGES }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: './apps/web'
          directory: '.svelte-kit/cloudflare'
          projectName: ${{ secrets.CLOUDFLARE_PROJECT_NAME }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          wranglerVersion: '3'
      - name: Publish API
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN_WORKERS }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: './apps/api'
