on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Not currently needed, but will in near future
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Install dependencies
        run: npm install
      # Testing Turborepo - probably overkill - NPM Workspaces would work just fine as well
      # v0 POC target web app only
      - name: Lint
        run: npx turbo run lint --filter=web
      - name: Build
        run: npx turbo run build --filter=web
      - name: Publish
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: 'grantmakers-next-poc-svelte-webapp-v0'
          directory: '.svelte-kit/cloudflare'
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
